// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system_settings.sql

package database

import (
	"context"
	"database/sql"
)

const deleteSystemSetting = `-- name: DeleteSystemSetting :exec
DELETE FROM system_settings
WHERE category = $1 AND key = $2
`

type DeleteSystemSettingParams struct {
	Category string `json:"category"`
	Key      string `json:"key"`
}

func (q *Queries) DeleteSystemSetting(ctx context.Context, arg DeleteSystemSettingParams) error {
	_, err := q.db.ExecContext(ctx, deleteSystemSetting, arg.Category, arg.Key)
	return err
}

const deleteSystemSettingsByCategory = `-- name: DeleteSystemSettingsByCategory :exec
DELETE FROM system_settings
WHERE category = $1
`

func (q *Queries) DeleteSystemSettingsByCategory(ctx context.Context, category string) error {
	_, err := q.db.ExecContext(ctx, deleteSystemSettingsByCategory, category)
	return err
}

const getSystemSetting = `-- name: GetSystemSetting :one
SELECT id, category, key, value, is_secret, updated_by, created_at, updated_at
FROM system_settings
WHERE category = $1 AND key = $2
`

type GetSystemSettingParams struct {
	Category string `json:"category"`
	Key      string `json:"key"`
}

func (q *Queries) GetSystemSetting(ctx context.Context, arg GetSystemSettingParams) (SystemSetting, error) {
	row := q.db.QueryRowContext(ctx, getSystemSetting, arg.Category, arg.Key)
	var i SystemSetting
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.Key,
		&i.Value,
		&i.IsSecret,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSystemSettings = `-- name: ListSystemSettings :many
SELECT id, category, key, value, is_secret, updated_by, created_at, updated_at
FROM system_settings
ORDER BY category ASC, key ASC
`

func (q *Queries) ListSystemSettings(ctx context.Context) ([]SystemSetting, error) {
	rows, err := q.db.QueryContext(ctx, listSystemSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemSetting
	for rows.Next() {
		var i SystemSetting
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Key,
			&i.Value,
			&i.IsSecret,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemSettingsByCategory = `-- name: ListSystemSettingsByCategory :many
SELECT id, category, key, value, is_secret, updated_by, created_at, updated_at
FROM system_settings
WHERE category = $1
ORDER BY key ASC
`

func (q *Queries) ListSystemSettingsByCategory(ctx context.Context, category string) ([]SystemSetting, error) {
	rows, err := q.db.QueryContext(ctx, listSystemSettingsByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemSetting
	for rows.Next() {
		var i SystemSetting
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Key,
			&i.Value,
			&i.IsSecret,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSystemSetting = `-- name: UpsertSystemSetting :one
INSERT INTO system_settings (
  category,
  key,
  value,
  is_secret,
  updated_by
) VALUES (
  $1, $2, $3, $4, $5
)
ON CONFLICT (category, key) DO UPDATE
  SET value = EXCLUDED.value,
      is_secret = EXCLUDED.is_secret,
      updated_by = EXCLUDED.updated_by
RETURNING id, category, key, value, is_secret, updated_by, created_at, updated_at
`

type UpsertSystemSettingParams struct {
	Category  string        `json:"category"`
	Key       string        `json:"key"`
	Value     string        `json:"value"`
	IsSecret  bool          `json:"is_secret"`
	UpdatedBy sql.NullInt64 `json:"updated_by"`
}

func (q *Queries) UpsertSystemSetting(ctx context.Context, arg UpsertSystemSettingParams) (SystemSetting, error) {
	row := q.db.QueryRowContext(ctx, upsertSystemSetting,
		arg.Category,
		arg.Key,
		arg.Value,
		arg.IsSecret,
		arg.UpdatedBy,
	)
	var i SystemSetting
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.Key,
		&i.Value,
		&i.IsSecret,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
